rapids-github-run-id: stop differentiating by triggering event (#196)
Co-authored-by: Kyle Edwards <kyedwards@nvidia.com>

diff --git a/tools/rapids-github-run-id b/tools/rapids-github-run-id
--- a/tools/rapids-github-run-id
+++ b/tools/rapids-github-run-id
@@ -1,8 +1,9 @@
 #!/bin/bash
 # Determines the GitHub Actions run ID to use in operations with the GitHub API.
 #
-# When environment variable GITHUB_RUN_ID is defined, just returns that value (except for on nightly builds... see below).
-# GITHUB_RUN_ID is set automatically on GitHub Actions.
+# When running in CI and fetching artifacts generated by other jobs in the same workflow run,
+# just returns the value of environment variable GITHUB_RUN_ID.
+#
 # ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
 #
 # Otherwise, tries to determine a run ID based on other context in the environment.
@@ -22,61 +23,71 @@ export RAPIDS_SCRIPT_NAME="rapids-github-run-id"
 
 rapids-prompt-local-github-auth
 
-# While called by CI, all the environment variables are set by the caller. However when run locally, these environment variables are set by rapids-prompt-local-repo-config
-case "${RAPIDS_BUILD_TYPE}" in
-  pull-request)
-    run_id=${GITHUB_RUN_ID:-$(
-      RAPIDS_RETRY_SLEEP=120                                  \
-        rapids-retry --quiet gh run list                      \
-          --repo "${RAPIDS_REPOSITORY}"                       \
-          --branch "${RAPIDS_REF_NAME}"                       \
-          --commit "${RAPIDS_SHA}"                            \
-          --workflow "${RAPIDS_BUILD_WORKFLOW_NAME:-pr.yaml}" \
-          --json 'createdAt,databaseId'                       \
-          --jq 'sort_by(.createdAt) | reverse | .[0] | .databaseId')}
-    ;;
-  branch)
-    run_id=${GITHUB_RUN_ID:-$(
-      RAPIDS_RETRY_SLEEP=120                                     \
-        rapids-retry --quiet gh run list                         \
-          --repo "${RAPIDS_REPOSITORY}"                          \
-          --branch "${RAPIDS_REF_NAME}"                          \
-          --commit "${RAPIDS_SHA}"                               \
-          --workflow "${RAPIDS_BUILD_WORKFLOW_NAME:-build.yaml}" \
-          --event "push"                                         \
-          --json 'createdAt,databaseId'                          \
-          --jq 'sort_by(.createdAt) | reverse | .[0] | .databaseId')}
-    ;;
-  nightly)
-    # Notice that for nightly runs, this script intentionally does not return GITHUB_RUN_ID.
-    #
-    # In RAPIDS CI, projects often have 2 separate workflows for nightlies:
-    #
-    #   * build.yaml = builds and uploads packages
-    #   * test.yaml  = installs nightly packages and runs tests
-    #
-    # From GitHub's perspective, those are different "runs", with different IDs.
-    # GitHub Actions organizes artifacts by run ID.
-    run_id=$(
-      RAPIDS_RETRY_SLEEP=120                                     \
-        rapids-retry --quiet gh run list                         \
-          --repo "${RAPIDS_REPOSITORY}"                          \
-          --branch "${RAPIDS_REF_NAME}"                          \
-          --commit "${RAPIDS_SHA}"                               \
-          --workflow "${RAPIDS_BUILD_WORKFLOW_NAME:-build.yaml}" \
-          --event "workflow_dispatch"                            \
-          --json 'createdAt,databaseId'                          \
-          --jq 'sort_by(.createdAt) | reverse | .[0] | .databaseId'
-    )
-    ;;
-  *)
-    rapids-echo-stderr "RAPIDS_BUILD_TYPE must be one of [branch, nightly, pull-request]"
-    exit 1
-    ;;
-esac
+# if RAPIDS_BUILD_WORKFLOW_NAME is set, use that instead of any RAPIDS conventions
+if [[ -n "${RAPIDS_BUILD_WORKFLOW_NAME:-}" ]]; then
+  workflow_that_produced_artifacts="${RAPIDS_BUILD_WORKFLOW_NAME}"
+  workflow_that_produced_artifacts_regex="\\.github/workflows/${workflow_that_produced_artifacts}"
+else
+  # otherwise, rely on the RAPIDS workflow name conventions
+  case "${RAPIDS_BUILD_TYPE}" in
+    pull-request)
+      workflow_that_produced_artifacts="pr.yaml"
+      workflow_that_produced_artifacts_regex="\\.github/workflows/pr\\.yaml"
+      ;;
+    branch|nightly)
+      workflow_that_produced_artifacts="build.yaml"
+      workflow_that_produced_artifacts_regex="\\.github/workflows/build\\.yaml"
+      ;;
+    *)
+      rapids-echo-stderr "RAPIDS_BUILD_TYPE must be one of [branch, nightly, pull-request]"
+      exit 1
+      ;;
+  esac
+fi
+
+# If the workflow we want artifacts from is the same one that's currently running, just
+# use GITHUB_RUN_ID. This prevents a network call to the GitHub API, which reduces the risk of
+# hitting temporary network issues and reduces the risk of hitting rate limits.
+#
+# In normal use, GITHUB_WORKFLOW_REF will have a value similar to:
+#
+#    GITHUB_WORKFLOW_REF=rapidsai/cudf/.github/workflows/pr.yaml@refs/heads/pull-request/19146
+#
+#    or
+#
+#    GITHUB_WORKFLOW_REF=rapidsai/cudf/.github/workflows/build.yaml@refs/heads/branch-25.08
+#
+# docs on 'GITHUB_WORKFLOW_REF': https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables
+#
+if [[ -n "${GITHUB_WORKFLOW_REF:-}" ]] && \
+    [[ -n "${GITHUB_RUN_ID:-}" ]] && \
+    [[ "${GITHUB_WORKFLOW_REF:-}" =~ ${workflow_that_produced_artifacts_regex} ]];
+then
+  run_id="${GITHUB_RUN_ID}"
+  rapids-echo-stderr "Assuming artifacts should be fetched from this same run of '${workflow_that_produced_artifacts}'"
+else
+  # Otherwise, need to look it up via the GitHub API.
+  #
+  # For example, RAPIDS nightly tests (by convention, 'test.yaml'), would fall here.
+  #
+  # On those types of runs, get the artifacts from the most recent run on a given
+  # branch and commit, without worrying about whether that was technically a 'branch' (triggered by a merge)
+  # or 'nightly' (triggered by a schedule) run.
+  rapids-echo-stderr "Querying the GitHub API to determine relevant run of '${workflow_that_produced_artifacts}'."
+  run_id=$(
+    RAPIDS_RETRY_SLEEP=120                                     \
+      rapids-retry --quiet gh run list                         \
+        --repo "${RAPIDS_REPOSITORY}"                          \
+        --branch "${RAPIDS_REF_NAME}"                          \
+        --commit "${RAPIDS_SHA}"                               \
+        --workflow "${workflow_that_produced_artifacts}"       \
+        --json 'createdAt,databaseId'                          \
+        --jq 'sort_by(.createdAt) | reverse | .[0] | .databaseId'
+  )
+fi
 
 if [[ -z "${run_id}" ]]; then
-  rapids-echo-stderr "ERROR: failed to find a GitHub Actions run for [RAPIDS_BUILD_TYPE=${RAPIDS_BUILD_TYPE}, RAPID_REPOSITORY=${RAPIDS_REPOSITORY}, RAPIDS_REF_NAME=${RAPIDS_REF_NAME}, RAPIDS_SHA=${RAPIDS_SHA}]"
+  rapids-echo-stderr "ERROR: failed to find a GitHub Actions run for [RAPIDS_BUILD_TYPE=${RAPIDS_BUILD_TYPE}, RAPIDS_REPOSITORY=${RAPIDS_REPOSITORY}, RAPIDS_REF_NAME=${RAPIDS_REF_NAME}, RAPIDS_SHA=${RAPIDS_SHA}]"
   exit 1
 fi
 
