allow upload/download wheels to work locally

diff --git a/tools/rapids-download-wheels-from-s3 b/tools/rapids-download-wheels-from-s3
--- a/tools/rapids-download-wheels-from-s3
+++ b/tools/rapids-download-wheels-from-s3
@@ -4,6 +4,64 @@
 #   1) dest dir to download and extract wheels to
 set -eo pipefail
 
+if [ "${CI:-false}" = "false" ]; then
+  rapids-echo-stderr "Local run detected."
+  rapids-echo-stderr "NVIDIA VPN connectivity is required to download workflow artifacts."
+
+  if [ -z "${RAPIDS_BUILD_TYPE:-}" ]; then
+    {
+      echo ""
+      read -r -p "Enter workflow type (one of: pull-request|branch|nightly): " RAPIDS_BUILD_TYPE
+      export RAPIDS_BUILD_TYPE
+      echo ""
+      echo "Suppress this prompt in the future by setting the 'RAPIDS_BUILD_TYPE' environment variable:"
+      echo "export RAPIDS_BUILD_TYPE=${RAPIDS_BUILD_TYPE}"
+      echo ""
+    } >&2
+  fi
+
+  if [ -z "${RAPIDS_REPOSITORY:-}" ]; then
+    {
+      echo ""
+      read -r -p "Enter org/repository name (e.g. rapidsai/cudf): " RAPIDS_REPOSITORY
+      export RAPIDS_REPOSITORY
+      echo ""
+      echo "Suppress this prompt in the future by setting the 'RAPIDS_REPOSITORY' environment variable:"
+      echo "export RAPIDS_REPOSITORY=${RAPIDS_REPOSITORY}"
+      echo ""
+    } >&2
+  fi
+
+  if [ -z "${RAPIDS_REF_NAME:-}" ]; then
+    {
+      echo ""
+      read -r -p "Enter pull-request number (e.g. 1546): " PR_NUMBER
+      RAPIDS_REF_NAME=pull-request/${PR_NUMBER}
+      export RAPIDS_REF_NAME
+      echo ""
+      echo "Suppress this prompt in the future by setting the 'RAPIDS_REF_NAME' environment variable:"
+      echo "export RAPIDS_REF_NAME=${RAPIDS_REF_NAME}"
+      echo ""
+    } >&2
+  fi
+
+  if [ -z "${RAPIDS_SHA:-}" ]; then
+    {
+      echo ""
+      if RAPIDS_SHA=$(set -e; git rev-parse HEAD 2> /dev/null); then
+        echo "Using HEAD commit for artifact commit hash. Overwrite this by setting the 'RAPIDS_SHA' environment variable:"
+        echo "export RAPIDS_SHA=${RAPIDS_SHA}"
+      else
+        echo "There was a problem acquiring the HEAD commit sha from the current directory."
+        echo "Suppress this prompt in the future by ensuring the current directory is the '${RAPIDS_REPOSITORY}' git repository."
+        read -r -p "Enter full commit sha (e.g. f15776cc449b0c8345f044f713c9c06eb13622f3): " RAPIDS_SHA
+      fi
+      echo ""
+      export RAPIDS_SHA
+    } >&2
+  fi
+fi
+
 pkg_name="$(rapids-package-name wheel_python)"
 
 rapids-download-from-s3 "${pkg_name}" "$@"
