Rework anaconda auth in rapids-upload-to-anaconda

diff --git a/tools/rapids-upload-to-anaconda b/tools/rapids-upload-to-anaconda
--- a/tools/rapids-upload-to-anaconda
+++ b/tools/rapids-upload-to-anaconda
@@ -5,21 +5,27 @@
 #   1) a directory path to search for conda packages
 set -e
 
+ECHO_PREFIX="    [rapids-upload-to-anaconda] "
 SEARCH_DIR="$1"
 
 if [ -z "${SEARCH_DIR}" ]; then
-  echo "Please provide a search directory."
+  rapids-echo-stderr "${ECHO_PREFIX}Please provide a search directory."
+  exit 1
+fi
+
+if [ ! -v CONDA_TOKEN ] | [ -z "${CONDA_TOKEN}" ]; then
+  rapids-echo-stderr "${ECHO_PREFIX}Env var CONDA_TOKEN must be set and not empty"
   exit 1
 fi
 
 if [ ! -d "${SEARCH_DIR}" ]; then
-  echo "Directory ${SEARCH_DIR} does not exist."
+  rapids-echo-stderr "${ECHO_PREFIX}Directory ${SEARCH_DIR} does not exist."
   exit 1
 fi
 
 PKGS_TO_UPLOAD=$(find "${SEARCH_DIR}" -name "*.tar.bz2")
 if [ -z "${PKGS_TO_UPLOAD}" ]; then
-  echo "Couldn't find any packages to upload in: ${SEARCH_DIR}."
+  rapids-echo-stderr "${ECHO_PREFIX}Couldn't find any packages to upload in: ${SEARCH_DIR}."
   ls -l "${SEARCH_DIR}/"*
   exit 1
 fi
@@ -30,24 +36,16 @@ case "${BUILD_TYPE}" in
   nightly)
     ;;
   *)
-    echo 'Only branch builds and nightly builds are uploaded to Anaconda.org'
+    rapids-echo-stderr "${ECHO_PREFIX}Only branch builds and nightly builds are uploaded to Anaconda.org"
     exit 1
     ;;
 esac
 
-CONDA_USERNAME="rapidsai-nightly"
-CONDA_TOKEN="${NIGHTLY_CONDA_TOKEN}"
-if [[ "${GIT_BRANCH}" == "main" ]]; then
-  CONDA_USERNAME="rapidsai"
-  CONDA_TOKEN="${STABLE_CONDA_TOKEN}"
-fi
-
-rapids-echo-stderr "Uploading packages to Anaconda.org: ${PKGS_TO_UPLOAD}"
+rapids-echo-stderr "${ECHO_PREFIX}Uploading packages to Anaconda.org: ${PKGS_TO_UPLOAD}"
 # shellcheck disable=SC2086
 anaconda \
   -t "${CONDA_TOKEN}" \
   upload \
-  -u "${CONDA_USERNAME}" \
   --label "${CONDA_UPLOAD_LABEL:-main}" \
   --skip-existing \
   --no-progress \
