feat(package-name): add support for limited api naming

diff --git a/tools/rapids-package-name b/tools/rapids-package-name
--- a/tools/rapids-package-name
+++ b/tools/rapids-package-name
@@ -5,6 +5,7 @@
 #   2) repo_name (optional): overrides repo name derived from RAPIDS_REPOSITORY
 # Flags:
 #   --pure: treats conda_python as noarch and wheel_python as pure
+#   --stable: package uses the Python limited API
 #   --cuda [version]: appends CUDA suffix processed by rapids-wheel-ctk-name-gen
 #                     if no version provided, uses RAPIDS_CUDA_VERSION
 set -euo pipefail
@@ -12,6 +13,7 @@ export RAPIDS_SCRIPT_NAME="rapids-package-name"
 
 is_pure_flag=0
 cuda_flag=0
+sabi_flag=0
 cuda_version=""
 pkg_type=""
 repo_name=""
@@ -20,6 +22,10 @@ while [[ $# -gt 0 ]]; do
   case $1 in
     --pure)
       is_pure_flag=1
+      shift
+      ;;
+    --stable)
+      sabi_flag=1
       shift
       ;;
     --cuda)
@@ -35,7 +41,7 @@ while [[ $# -gt 0 ]]; do
       fi
       ;;
     -*)
-      rapids-echo-stderr "Unknown flag: $1. Supported flags: --pure, --cuda"
+      rapids-echo-stderr "Unknown flag: $1. Supported flags: --pure, --stable, --cuda"
       exit 1
       ;;
     *)
@@ -54,8 +60,19 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
+# Error checking
 if [[ -z "${pkg_type}" ]]; then
-  rapids-echo-stderr "Must specify input arguments: PKG_TYPE [REPO_NAME] [--pure] [--cuda [version]]"
+  rapids-echo-stderr "Must specify input arguments: PKG_TYPE [REPO_NAME] [--pure] [--stable] [--cuda [version]]"
+  exit 1
+fi
+
+if (( sabi_flag == 1)) && (( is_pure_flag == 1)); then
+  rapids-echo-stderr "Cannot use '--pure' with '--stable', you must choose one or the other"
+  exit 1
+fi
+
+if (( sabi_flag == 1)) && [[ $pkg_type == "conda_cpp" || $pkg_type == "wheel_cpp" ]]; then
+  rapids-echo-stderr "'--stable' is only compatible with Python package builds"
   exit 1
 fi
 
@@ -92,6 +109,7 @@ append_wheelname=0
 append_pyver=0
 append_arch=0
 append_noarch=0
+append_stable=0
 
 case "${pkg_type}" in
   conda_cpp)
@@ -107,6 +125,11 @@ case "${pkg_type}" in
     else
       append_noarch=1
     fi
+    if (( sabi_flag == 1 )); then
+      append_stable=1
+      append_cuda=0
+      append_pyver=0
+    fi
     ;;
   wheel_cpp)
     append_wheelname=1
@@ -118,6 +141,10 @@ case "${pkg_type}" in
     if (( is_pure_wheel == 0 )); then
       append_pyver=1
       append_arch=1
+    fi
+    if (( sabi_flag == 1 )); then
+      append_stable=1
+      append_pyver=0
     fi
     ;;
   *)
@@ -137,6 +164,7 @@ if (( use_custom_conda_name == 1 )); then
   append_pyver=0
   append_arch=0
   append_noarch=0
+  append_stable=0
 fi
 
 # for conda package types, append CUDA version
@@ -152,6 +180,11 @@ fi
 # for python package types (except pure wheels), add pyver
 if (( append_pyver == 1 )); then
   pkg_name+="_py${RAPIDS_PY_VERSION//./}"
+fi
+
+# for cpp and python wheels, append `abi3`
+if (( append_stable == 1)); then
+  pkg_name+="_abi3"
 fi
 
 # for cpp and python package types (except pure wheels), append the arch of the host that's running the upload command
